- hosts: node01
  gather_facts: true
  vars_prompt:
    name: input
    prompt: Enter input
    private: no
  tasks:
    - debug:
        var: input
    - name: Create user
      user:
        name: {{input}}
    - file:
        path: /tmp/{{input}}.txt
        mode: 644
    - debug:
        var: ansible_default_ipv4.address
    - name: Change hostname
      shell: hostname {{input}}