 - hosts: node01
   gather_facts: true
   become: true
   vars:
     httpd_port: 8080
   tasks:
    - name: Make directory
      shell: mkdir -p /home/ec2-user/testdirAnsible

    - name: Copy inventory
      copy: src=../inventory/ansible-nodes dest=/tmp/ansible-nodes

    - name: Cat
      shell: cat /tmp/ansible-nodes

    - yum:
        pkg: httpd
        state: present

    - yum:
        pkg: git
        state: present

    - name: Git_repo
      ansible.builtin.git:
        repo: https://github.com/becloudready/prometheus_monitoring.git
        dest: /tmp1
        version: HEAD