---
- hosts: node01
  gather_facts: false
  tasks:
  - name: Install packages
    pkg: item
    with_items:
    - mlocate
    - strace
    - java 8
    - php 5
  
  - name: Create folders
    shell: mkdir -p /home/ec2-user/{{item}}
    with_items:
    - yelp
    - google
    - apple
    - yahoo
    - allstate