---
- name: install tomcat server
  hosts: node01
  become: true

  tasks:
  - name: Install OpenJDK
    package:
      name: java-11-openjdk
      state: present

  - name: download tomcat server packages
    get_url:
      url: https://downloads.apache.org/tomcat/tomcat-9/v9.0.50/bin/apache-tomcat-9.0.50.tar.gz
      dest: /usr/local

  - name: extract tomcat packages
    unarchive:
      src: /usr/local/apache-tomcat-9.0.44.tar.gz
      dest: /usr/local
      remote_src: yes

  - name: start tomcat services
    shell: nohup /usr/local/apache-tomcat-9.0.44/bin/startup.sh