- hosts: webservers
  vars:
    user_name: Paul
  tasks:
    - template:
        src: httpd.conf.j2
        dest: /tmp/jinta-output
    - debug: var=play_hosts
    - service:
        name: httpd
        state: restarted
